### ISSUE TITLE
Error in bgm using matrix for inclusion_probability

### ISSUE THREAD

**Issue by martinobelvederi** [cran/bgms#1]
Hello and congratulations for the really nice package! 
second time I post an issue, so hope to do it right. 
I'm trying to provide a matrix of inclusion probabilities for each edge in the bernoulli model. Despite providing a matrix with or without col/rownames,  I receive an error "_The input for the inclusion probability argument needs to be a single number, matrix, or dataframe."_

here is what I hope is a reproducible example
thanks a lot in advance! Martino

set.seed(123) # For reproducibility
db1_sample <- matrix(sample(0:1, 600, replace = TRUE), nrow=50, ncol=12)
mat1_sample <- matrix(runif(min = 0, max = 1, n = 144), ncol = 12)
diag(mat1_sample) <- 1
mat1_sample[upper.tri(mat1_sample)] <- t(mat1_sample)[upper.tri(mat1_sample)]
isSymmetric(mat1_sample)

#Reproduce the issue
net.bern2 <- bgm(x = as.matrix(db1_sample), 
                 inclusion_probability = mat1_sample)

> net.bern2 <- bgm(x = db1_sample, inclusion_probability = mat1_sample)
# Error in bgm(x = as.matrix(db1_sample), inclusion_probability = mat1_sample) : 
 # The input for the inclusion probability argument needs to be a single number, matrix, or dataframe.

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by martinobelvederi** [comment]
sorry! thanks
